services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_ENV: ${API_ENV}
      PORT: ${API_PORT}
      CHOCLACADO_DB_HOST: ${CHOCLACADO_DB_HOST}
      CHOCLACADO_DB_PORT: ${CHOCLACADO_DB_PORT}
      CHOCLACADO_DB_DATABASE: ${CHOCLACADO_DB_DATABASE}
      CHOCLACADO_DB_USERNAME: ${CHOCLACADO_DB_USERNAME}
      CHOCLACADO_DB_PASSWORD: ${CHOCLACADO_DB_PASSWORD}
      CHOCLACADO_DB_SCHEMA: ${CHOCLACADO_DB_SCHEMA}
      BETTER_AUTH_JWT_URL: ${BETTER_AUTH_JWT_URL}
    depends_on:
      psql_c:
        condition: service_healthy
    networks:
      - choclacado
  frontend:
    build:
      target: prod
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: http://api:${API_PORT}
      NODE_ENV: production
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      CHOCLACADO_DB_HOST: ${CHOCLACADO_DB_HOST}
      CHOCLACADO_DB_PORT: ${CHOCLACADO_DB_PORT}
      CHOCLACADO_DB_DATABASE: ${CHOCLACADO_DB_DATABASE}
      CHOCLACADO_DB_USERNAME: ${CHOCLACADO_DB_USERNAME}
      CHOCLACADO_DB_PASSWORD: ${CHOCLACADO_DB_PASSWORD}
      CHOCLACADO_DB_SCHEMA: ${CHOCLACADO_DB_SCHEMA}
    expose:
      - "4242"
    depends_on:
      api:
        condition: service_started
    networks:
      - choclacado
    deploy:
      replicas: 3
  psql_c:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CHOCLACADO_DB_DATABASE}
      POSTGRES_USER: ${CHOCLACADO_DB_USERNAME}
      POSTGRES_PASSWORD: ${CHOCLACADO_DB_PASSWORD}
    expose:
      - "5432"
    volumes:
      - psql_volume_c:/var/lib/postgresql/data_c
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${CHOCLACADO_DB_USERNAME} -d ${CHOCLACADO_DB_DATABASE}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - choclacado

volumes:
  psql_volume_c:
networks:
  choclacado:
