services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      CHOCLACADO_DB_HOST: ${CHOCLACADO_DB_HOST}
      CHOCLACADO_DB_PORT: ${CHOCLACADO_DB_PORT}
      CHOCLACADO_DB_DATABASE: ${CHOCLACADO_DB_DATABASE}
      CHOCLACADO_DB_USERNAME: ${CHOCLACADO_DB_USERNAME}
      CHOCLACADO_DB_PASSWORD: ${CHOCLACADO_DB_PASSWORD}
      CHOCLACADO_DB_SCHEMA: ${CHOCLACADO_DB_SCHEMA}
    depends_on:
      psql_bp:
        condition: service_healthy
    networks:
      - choclacado
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CHOCLACADO_DB_DATABASE}
      POSTGRES_USER: ${CHOCLACADO_DB_USERNAME}
      POSTGRES_PASSWORD: ${CHOCLACADO_DB_PASSWORD}
    ports:
      - "${CHOCLACADO_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${CHOCLACADO_DB_USERNAME} -d ${CHOCLACADO_DB_DATABASE}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - choclacado

volumes:
  psql_volume_bp:
networks:
  choclacado:
