services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_ENV: ${API_ENV}
      PORT: ${API_PORT}
      CHOCLACADO_DB_HOST: ${CHOCLACADO_DB_HOST}
      CHOCLACADO_DB_PORT: ${CHOCLACADO_DB_PORT}
      CHOCLACADO_DB_DATABASE: ${CHOCLACADO_DB_DATABASE}
      CHOCLACADO_DB_USERNAME: ${CHOCLACADO_DB_USERNAME}
      CHOCLACADO_DB_PASSWORD: ${CHOCLACADO_DB_PASSWORD}
      CHOCLACADO_DB_SCHEMA: ${CHOCLACADO_DB_SCHEMA}
    depends_on:
      psql_c:
        condition: service_healthy
    networks:
      - choclacado
    develop:
      watch:
        - action: sync+restart
          path: ./cmd
          target: /app/cmd
        - action: sync+restart
          path: ./internal
          target: /app/internal
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum

  frontend:
    build:
      target: dev
      context: ./frontend
      dockerfile: Dockerfile
    command: ["pnpm", "run", "dev"]
    environment:
      API_URL: http://api:${API_PORT}
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    networks:
      - choclacado
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json
  psql_c:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CHOCLACADO_DB_DATABASE}
      POSTGRES_USER: ${CHOCLACADO_DB_USERNAME}
      POSTGRES_PASSWORD: ${CHOCLACADO_DB_PASSWORD}
    ports:
      - "${CHOCLACADO_DB_PORT}:5432"
    volumes:
      - psql_volume_c:/var/lib/postgresql/data_c
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${CHOCLACADO_DB_USERNAME} -d ${CHOCLACADO_DB_DATABASE}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - choclacado

volumes:
  psql_volume_c:
networks:
  choclacado:
